### ISSUE TITLE
Suggestion: Allow a Melee launch from Steam

### ISSUE THREAD

**Issue by davidvkimball** [RucksP/Instant_Melee#1]
Hey there! I love this. 

I'm wondering if there's a way to modify the config.txt to launch Slippi as a custom game through Steam. I was trying to replace my Dolphin path with the following:

`"C:\Program Files (x86)\Steam\Steam.exe" -gameidlaunch 13493096156527329280`

But it didn't work. This works just fine as a shortcut in Windows to launch Melee since I added it as a non-Steam game to my library. 

Any chance you could include support for this?

**Comment by RucksP** [comment]
I should be able to add this later today

**Comment by RucksP** [comment]
It was pretty simple to let you open the game once via steam, but launching through steam doesn't give me a way to see if dolphin is still running or not so the program will close after opening dolphin once. Don't think there's an easy way around that unless you could somehow guarantee everyone had the same gameid for melee.

**Comment by davidvkimball** [comment]
Understood, thanks for giving it a shot at least!
